### ISSUE TITLE
Build on macos hight sierra 10.13.4

### ISSUE THREAD

**Issue by J6rry** [LarsFlaeten/ork#3]
According to <Installation.txt>, I installed the dependiences with `brew install`.
Then `mkdir build` -> `cd build` -> `cmake ..`
No errors, I compile with `make`
It stopped with the error: Object.h:53:10: fatal error: 'tr1/memory'     file not found

Any suggestion?

**Comment by LarsFlaeten** [comment]
Hi, this has not been tested on Mac i believe. Try to add the following lines in Object.h after line 51:
````
#elif __APPLE__
#include <memory>
#define TR1 std
````
